### Get all friends
GET  http://localhost:3000/friends

### Get a friend by id
GET  http://localhost:3000/friends/1

### Create a new friend
POST http://localhost:3000/friends
Content-Type: application/json

{
    "name": "Marie Curie"
}