### Get launches
GET http://localhost:8000/v1/launches?page=1&limit=50

### Add a new launch
POST http://localhost:8000/v1/launches
Content-Type: application/json

{
    "mission": "ZTM155",
    "rocket": "ZTM Experimental IS1",
    "target": "Kepler-1652 b",
    "launchDate": "January 17, 2030"
}

### Abort a launch
DELETE http://localhost:8000/vi/launches/3


### Get plannets
GET http://localhost:8000/v1/planets